<a href="https://colab.research.google.com/github/Ragorfish/Pyhton-Developement-Intern/blob/main/NumPy_Assignment_MohitSisodia.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#1. . Create a NumPy array 'arr' of integers from 0 to 5 and print its data type.

In [1]:
import numpy as np

# Create the NumPy array
arr = np.array(range(6))

# Print the data type of the array
print("Array:", arr)
print("Data type:", arr.dtype)


Array: [0 1 2 3 4 5]
Data type: int64


In [2]:
#2. Given a NumPy array 'arr', check if its data type is float64.
#   arr = np.array([1.5, 2.6, 3.7])

In [3]:
import numpy as np

# Given NumPy array
arr = np.array([1.5, 2.6, 3.7])

# Check if the data type is float64
if arr.dtype == np.float64:
    print("The data type of 'arr' is float64.")
else:
    print("The data type of 'arr' is not float64.")


The data type of 'arr' is float64.


In [4]:
#3.  Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

In [5]:
import numpy as np

# Create the NumPy array with complex128 data type
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)

# Print the array and its data type
print("Array:", arr)
print("Data type:", arr.dtype)


Array: [1.+2.j 3.+4.j 5.+6.j]
Data type: complex128


In [6]:
#4. Convert an existing NumPy array 'arr' of integers to float32 data type.

In [7]:
import numpy as np

# Existing NumPy array of integers
arr = np.array([1, 2, 3, 4, 5])

# Convert to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the converted array and its data type
print("Original array:", arr)
print("Original data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)


Original array: [1 2 3 4 5]
Original data type: int64
Converted array: [1. 2. 3. 4. 5.]
Converted data type: float32


In [8]:
#5.  Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

In [9]:
import numpy as np

# Given NumPy array with float64 data type
arr = np.array([1.123456789, 2.987654321, 3.456789123], dtype=np.float64)

# Convert to float32 to reduce precision
arr_float32 = arr.astype(np.float32)

# Print the original and converted arrays along with their data types
print("Original array:", arr)
print("Original data type:", arr.dtype)
print("Converted array:", arr_float32)
print("Converted data type:", arr_float32.dtype)


Original array: [1.12345679 2.98765432 3.45678912]
Original data type: float64
Converted array: [1.1234568 2.9876542 3.456789 ]
Converted data type: float32


In [10]:
 #6.  Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
 #    type.

In [11]:
import numpy as np

def array_attributes(arr):
    """
    Function to return the shape, size, and data type of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the shape, size, and data type of the array.
    """
    shape = arr.shape
    size = arr.size
    dtype = arr.dtype
    return shape, size, dtype

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
shape, size, dtype = array_attributes(arr)
print("Shape:", shape)
print("Size:", size)
print("Data type:", dtype)


Shape: (2, 3)
Size: 6
Data type: int32


In [12]:
#7. Create a function array_dimension that takes a NumPy array as input and returns its dimensionality

In [13]:
import numpy as np

def array_dimension(arr):
    """
    Function to return the dimensionality of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        int: Dimensionality (number of axes) of the array.
    """
    return arr.ndim

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]])
dimensionality = array_dimension(arr)
print("Dimensionality of the array:", dimensionality)


Dimensionality of the array: 2


In [14]:
#8.  Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
#    size in bytes.

In [15]:
import numpy as np

def item_size_info(arr):
    """
    Function to return the item size and total size in bytes of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the item size (in bytes) and the total size (in bytes).
    """
    item_size = arr.itemsize  # Size of one array element in bytes
    total_size = arr.nbytes   # Total size of the array in bytes
    return item_size, total_size

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
item_size, total_size = item_size_info(arr)
print("Item size (in bytes):", item_size)
print("Total size (in bytes):", total_size)


Item size (in bytes): 4
Total size (in bytes): 24


In [16]:
#9.  Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

In [17]:
import numpy as np

def array_strides(arr):
    """
    Function to return the strides of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the strides of the array.
    """
    return arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
strides = array_strides(arr)
print("Strides of the array:", strides)


Strides of the array: (12, 4)


In [18]:
#10. Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
#    and strides of the array.

In [19]:
import numpy as np

def shape_stride_relationship(arr):
    """
    Function to return the shape and strides of a NumPy array.

    Parameters:
        arr (numpy.ndarray): Input NumPy array.

    Returns:
        tuple: A tuple containing the shape and strides of the array.
    """
    return arr.shape, arr.strides

# Example usage
arr = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.int32)
shape, strides = shape_stride_relationship(arr)
print("Shape of the array:", shape)
print("Strides of the array:", strides)


Shape of the array: (2, 3)
Strides of the array: (12, 4)


In [20]:
#11. Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
#    zeros with `n` elements.

In [21]:
import numpy as np

def create_zeros_array(n):
    """
    Function to create a NumPy array of zeros with n elements.

    Parameters:
        n (int): The number of elements in the array.

    Returns:
        numpy.ndarray: A NumPy array of zeros with n elements.
    """
    return np.zeros(n)

# Example usage
n = 5
zeros_array = create_zeros_array(n)
print("Array of zeros:", zeros_array)


Array of zeros: [0. 0. 0. 0. 0.]


In [22]:
#12.  Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
#NumPy array filled with ones of size `rows x cols`.

In [23]:
import numpy as np

def create_ones_matrix(rows, cols):
    """
    Function to create a 2D NumPy array filled with ones of size rows x cols.

    Parameters:
        rows (int): The number of rows in the array.
        cols (int): The number of columns in the array.

    Returns:
        numpy.ndarray: A 2D NumPy array of ones with the given size.
    """
    return np.ones((rows, cols))

# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)
print("Matrix of ones:\n", ones_matrix)


Matrix of ones:
 [[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


In [24]:
#13.  Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
#creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
#`step`.

In [25]:
import numpy as np

def generate_range_array(start, stop, step):
    """
    Function to generate a NumPy array with a range starting from 'start',
    ending at 'stop' (exclusive), and with the specified 'step'.

    Parameters:
        start (int): The starting value of the range.
        stop (int): The end value of the range (exclusive).
        step (int): The step size between elements.

    Returns:
        numpy.ndarray: A NumPy array with the specified range.
    """
    return np.arange(start, stop, step)

# Example usage
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)
print("Generated range array:", range_array)


Generated range array: [0 2 4 6 8]


In [26]:
#14.  Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
#arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
#(inclusive).

In [27]:
import numpy as np

def generate_linear_space(start, stop, num):
    """
    Function to generate a NumPy array with `num` equally spaced values between
    'start' and 'stop' (inclusive).

    Parameters:
        start (float): The starting value of the range.
        stop (float): The end value of the range (inclusive).
        num (int): The number of equally spaced values.

    Returns:
        numpy.ndarray: A NumPy array with `num` equally spaced values between `start` and `stop`.
    """
    return np.linspace(start, stop, num)

# Example usage
start = 0.0
stop = 10.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)
print("Generated linear space array:", linear_space_array)


Generated linear space array: [ 0.   2.5  5.   7.5 10. ]


In [28]:
#15.  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
#identity matrix of size `n x n` using `numpy.eye

In [29]:
import numpy as np

def create_identity_matrix(n):
    """
    Function to create a square identity matrix of size n x n.

    Parameters:
        n (int): The size of the identity matrix.

    Returns:
        numpy.ndarray: A square identity matrix of size n x n.
    """
    return np.eye(n)

# Example usage
n = 4
identity_matrix = create_identity_matrix(n)
print("Identity matrix of size", n, "x", n, ":\n", identity_matrix)


Identity matrix of size 4 x 4 :
 [[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [30]:
#16. Write a function that takes a Python list and converts it into a NumPy array.

In [31]:
import numpy as np

def list_to_array(py_list):
    """
    Function to convert a Python list into a NumPy array.

    Parameters:
        py_list (list): A Python list to be converted.

    Returns:
        numpy.ndarray: The NumPy array corresponding to the input list.
    """
    return np.array(py_list)

# Example usage
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_array(py_list)
print("Converted NumPy array:", numpy_array)


Converted NumPy array: [1 2 3 4 5]


In [32]:
#17. . Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
#same data.

In [33]:
import numpy as np

# Create a NumPy array
arr = np.array([1, 2, 3, 4, 5])

# Use view to create a new array with the same data
view_arr = arr.view()

# Modify an element in the original array
arr[0] = 99

# Print both arrays to show that they share the same data
print("Original array:", arr)
print("View array:", view_arr)


Original array: [99  2  3  4  5]
View array: [99  2  3  4  5]


In [34]:
#18. Write a function that takes two NumPy arrays and concatenates them along a specified axis.

In [35]:
import numpy as np

def concatenate_arrays(arr1, arr2, axis=0):
    """
    Function to concatenate two NumPy arrays along a specified axis.

    Parameters:
        arr1 (numpy.ndarray): The first NumPy array.
        arr2 (numpy.ndarray): The second NumPy array.
        axis (int): The axis along which the arrays should be concatenated (default is 0).

    Returns:
        numpy.ndarray: The concatenated NumPy array.
    """
    return np.concatenate((arr1, arr2), axis=axis)

# Example usage
arr1 = np.array([[1, 2], [3, 4]])
arr2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (rows)
concatenated_arr_0 = concatenate_arrays(arr1, arr2, axis=0)
print("Concatenated along axis 0:\n", concatenated_arr_0)

# Concatenate along axis 1 (columns)
concatenated_arr_1 = concatenate_arrays(arr1, arr2, axis=1)
print("Concatenated along axis 1:\n", concatenated_arr_1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]
Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [36]:
#19. Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.
#concatenate`.

In [37]:
import numpy as np

# Create two NumPy arrays with different shapes
arr1 = np.array([[1, 2], [3, 4]])  # Shape (2, 2)
arr2 = np.array([[5], [6]])        # Shape (2, 1)

# Concatenate them horizontally (along axis 1)
concatenated_arr = np.concatenate((arr1, arr2), axis=1)

print("Concatenated array along axis 1:\n", concatenated_arr)


Concatenated array along axis 1:
 [[1 2 5]
 [3 4 6]]


In [38]:
#20. Write a function that vertically stacks multiple NumPy arrays given as a list

In [39]:
import numpy as np

def vertical_stack_arrays(arrays):
    """
    Function to vertically stack multiple NumPy arrays provided as a list.

    Parameters:
        arrays (list): A list containing NumPy arrays to be vertically stacked.

    Returns:
        numpy.ndarray: The vertically stacked NumPy array.
    """
    return np.vstack(arrays)

# Example usage
arr1 = np.array([1, 2])
arr2 = np.array([3, 4])
arr3 = np.array([5, 6])

# List of arrays to be stacked
arrays = [arr1, arr2, arr3]

# Vertically stack the arrays
stacked_array = vertical_stack_arrays(arrays)
print("Vertically stacked array:\n", stacked_array)


Vertically stacked array:
 [[1 2]
 [3 4]
 [5 6]]


In [40]:
#21. Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
#with a given step size.

In [41]:
import numpy as np

def create_range_array(start, stop, step):
    """
    Function to create an array of integers within a specified range (inclusive) with a given step size.

    Parameters:
        start (int): The starting value of the range.
        stop (int): The ending value of the range (inclusive).
        step (int): The step size between consecutive values.

    Returns:
        numpy.ndarray: A NumPy array of integers within the specified range with the given step size.
    """
    return np.arange(start, stop + 1, step)

# Example usage
start = 1
stop = 10
step = 2

range_array = create_range_array(start, stop, step)
print("Array within the range:", range_array)


Array within the range: [1 3 5 7 9]


In [42]:
#22. Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
#(inclusive).

In [43]:
import numpy as np

def generate_equally_spaced_values():
    """
    Function to generate an array of 10 equally spaced values between 0 and 1 (inclusive).

    Returns:
        numpy.ndarray: A NumPy array of 10 equally spaced values between 0 and 1 (inclusive).
    """
    return np.linspace(0, 1, 10)

# Example usage
equally_spaced_values = generate_equally_spaced_values()
print("Equally spaced values:", equally_spaced_values)


Equally spaced values: [0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [44]:
#23. Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
#1000 (inclusive).

In [45]:
import numpy as np

def generate_log_spaced_values():
    """
    Function to generate an array of 5 logarithmically spaced values between 1 and 1000 (inclusive).

    Returns:
        numpy.ndarray: A NumPy array of 5 logarithmically spaced values between 1 and 1000 (inclusive).
    """
    return np.logspace(0, 3, 5)

# Example usage
log_spaced_values = generate_log_spaced_values()
print("Logarithmically spaced values:", log_spaced_values)


Logarithmically spaced values: [   1.            5.62341325   31.6227766   177.827941   1000.        ]


In [46]:
#24.  Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
#are random integers between 1 and 100.

In [47]:
import numpy as np
import pandas as pd

def create_dataframe():
    """
    Function to create a Pandas DataFrame using a NumPy array with random integers
    between 1 and 100, having 5 rows and 3 columns.

    Returns:
        pandas.DataFrame: The generated DataFrame.
    """
    # Generate a NumPy array of random integers between 1 and 100, shape (5, 3)
    random_array = np.random.randint(1, 101, size=(5, 3))

    # Create a DataFrame from the NumPy array
    df = pd.DataFrame(random_array, columns=['Column1', 'Column2', 'Column3'])

    return df

# Example usage
df = create_dataframe()
print("Generated DataFrame:\n", df)


Generated DataFrame:
    Column1  Column2  Column3
0       13       53       81
1       11       26       88
2       79       57       86
3       19       97       73
4       85       70       21


In [48]:
#25. Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
#with zeros. Use NumPy operations within the Pandas DataFrame.

In [49]:
import numpy as np
import pandas as pd

def replace_negative_with_zero(df, column_name):
    """
    Function to replace all negative values in a specific column of a Pandas DataFrame with zeros.

    Parameters:
        df (pandas.DataFrame): The DataFrame to modify.
        column_name (str): The column in which negative values will be replaced with zeros.

    Returns:
        pandas.DataFrame: The modified DataFrame with negative values replaced by zeros.
    """
    # Use NumPy's where to replace negative values with zero in the specified column
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])

    return df

# Example usage
data = {'Column1': [10, -5, 15, -3, 7],
        'Column2': [4, -2, 8, 9, -1]}

df = pd.DataFrame(data)

print("Original DataFrame:\n", df)

# Replace negative values in 'Column1' with zeros
df_modified = replace_negative_with_zero(df, 'Column1')

print("\nModified DataFrame:\n", df_modified)


Original DataFrame:
    Column1  Column2
0       10        4
1       -5       -2
2       15        8
3       -3        9
4        7       -1

Modified DataFrame:
    Column1  Column2
0       10        4
1        0       -2
2       15        8
3        0        9
4        7       -1


In [50]:
#26.  Access the 3rd element from the given NumPy array.
#     arr = np.array([10, 20, 30, 40, 50])

In [51]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

print("The 3rd element is:", third_element)


The 3rd element is: 30


In [52]:
#27. Retrieve the element at index (1, 2) from the 2D NumPy array.
#    arr_2d = np.array([[1, 2, 3],
                  # [4, 5, 6],
                  # [7, 8, 9]])arr_2d = np.array([[1, 2, 3],
                  # [4, 5, 6],
                  # [7, 8, 9]])

In [53]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

print("The element at index (1, 2) is:", element)


The element at index (1, 2) is: 6


In [54]:
#28. Using boolean indexing, extract elements greater than 5 from the given NumPy array.
# arr = np.array([3, 8, 2, 10, 5, 7])

In [55]:
import numpy as np

arr = np.array([3, 8, 2, 10, 5, 7])

# Use boolean indexing to extract elements greater than 5
filtered_elements = arr[arr > 5]

print("Elements greater than 5:", filtered_elements)


Elements greater than 5: [ 8 10  7]


In [56]:
#29.  Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
# arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])


In [57]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Perform basic slicing to extract elements from index 2 to 5 (inclusive)
sliced_array = arr[2:6]

print("Extracted elements:", sliced_array)


Extracted elements: [3 4 5 6]


In [58]:
#30.  Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array
#     arr_2d = np.array([[1, 2, 3],
#                   [4, 5, 6],
#                   [7, 8, 9]])

In [59]:
import numpy as np

arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice the array to extract the desired sub-array
sub_array = arr_2d[0:2, 1:3]

print("Extracted sub-array:\n", sub_array)


Extracted sub-array:
 [[2 3]
 [5 6]]


In [60]:
#31. Write a NumPy function to extract elements in specific order from a given 2D array based on indices
#provided in another array.

In [61]:
import numpy as np

def extract_elements(arr, indices):
    """
    Function to extract elements from a given 2D array based on indices provided in another array.

    Parameters:
        arr (numpy.ndarray): The 2D NumPy array to extract elements from.
        indices (numpy.ndarray): A 2D array of indices specifying which elements to extract.

    Returns:
        numpy.ndarray: A 1D array of extracted elements in the specified order.
    """
    # Use advanced indexing to extract the elements
    return arr[indices[:, 0], indices[:, 1]]

# Example usage
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

indices = np.array([[0, 1],  # Element at row 0, column 1
                    [2, 2],  # Element at row 2, column 2
                    [1, 0]]) # Element at row 1, column 0

extracted_elements = extract_elements(arr_2d, indices)
print("Extracted elements:", extracted_elements)


Extracted elements: [20 90 40]


In [62]:
#32. Create a NumPy function that filters elements greater than a threshold from a given 1D array using
#    boolean indexing.

In [63]:
import numpy as np

def filter_greater_than_threshold(arr, threshold):
    """
    Function to filter elements greater than a specified threshold from a 1D NumPy array.

    Parameters:
        arr (numpy.ndarray): The input 1D array.
        threshold (float): The threshold value.

    Returns:
        numpy.ndarray: A 1D array containing elements greater than the threshold.
    """
    # Use boolean indexing to filter elements greater than the threshold
    return arr[arr > threshold]

# Example usage
array = np.array([1, 5, 8, 3, 10, 2, 7])
threshold_value = 5

filtered_array = filter_greater_than_threshold(array, threshold_value)
print("Filtered array:", filtered_array)


Filtered array: [ 8 10  7]


In [64]:
#33.  Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
#     separate arrays for each dimension.

In [65]:
import numpy as np

def extract_elements_3d(arr, x_indices, y_indices, z_indices):
    """
    Function to extract specific elements from a 3D NumPy array using separate indices for each dimension.

    Parameters:
        arr (numpy.ndarray): The input 3D array.
        x_indices (numpy.ndarray): 1D array of indices for the first dimension (x-axis).
        y_indices (numpy.ndarray): 1D array of indices for the second dimension (y-axis).
        z_indices (numpy.ndarray): 1D array of indices for the third dimension (z-axis).

    Returns:
        numpy.ndarray: A 1D array of extracted elements.
    """
    # Use advanced indexing to extract elements
    return arr[x_indices, y_indices, z_indices]

# Example usage
arr_3d = np.array([[[10, 20, 30],
                    [40, 50, 60]],

                   [[70, 80, 90],
                    [100, 110, 120]]])

x_indices = np.array([0, 1, 1])  # Indices along the x-axis
y_indices = np.array([1, 0, 1])  # Indices along the y-axis
z_indices = np.array([2, 1, 0])  # Indices along the z-axis

extracted_elements = extract_elements_3d(arr_3d, x_indices, y_indices, z_indices)
print("Extracted elements:", extracted_elements)


Extracted elements: [ 60  80 100]


In [66]:
#34. Write a NumPy function that returns elements from an array where both two conditions are satisfied
#    using boolean indexing.

In [67]:
import numpy as np

def filter_with_conditions(arr, condition1, condition2):
    """
    Function to filter elements from a NumPy array where two conditions are satisfied.

    Parameters:
        arr (numpy.ndarray): The input 1D array.
        condition1 (callable): A function representing the first condition, e.g., lambda x: x > 5.
        condition2 (callable): A function representing the second condition, e.g., lambda x: x < 20.

    Returns:
        numpy.ndarray: A 1D array containing elements that satisfy both conditions.
    """
    # Combine the conditions using boolean indexing
    return arr[np.logical_and(condition1(arr), condition2(arr))]

# Example usage
array = np.array([1, 5, 8, 15, 20, 25, 3, 10])
filtered_array = filter_with_conditions(array, lambda x: x > 5, lambda x: x < 20)

print("Filtered elements:", filtered_array)


Filtered elements: [ 8 15 10]


In [68]:
#35.  Create a NumPy function that extracts elements from a 2D array using row and column indices provided
#     in separate arrays.

In [69]:
import numpy as np

def extract_elements_2d(arr, row_indices, col_indices):
    """
    Function to extract elements from a 2D NumPy array using separate row and column indices.

    Parameters:
        arr (numpy.ndarray): The input 2D array.
        row_indices (numpy.ndarray): 1D array of row indices.
        col_indices (numpy.ndarray): 1D array of column indices.

    Returns:
        numpy.ndarray: A 1D array of extracted elements.
    """
    # Use advanced indexing to extract elements
    return arr[row_indices, col_indices]

# Example usage
arr_2d = np.array([[10, 20, 30],
                   [40, 50, 60],
                   [70, 80, 90]])

row_indices = np.array([0, 1, 2])  # Row indices
col_indices = np.array([1, 2, 0])  # Column indices

extracted_elements = extract_elements_2d(arr_2d, row_indices, col_indices)
print("Extracted elements:", extracted_elements)


Extracted elements: [20 60 70]


In [70]:
#36. Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

In [71]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar value of 5 using broadcasting
result = arr + 5

print("Original array:\n", arr)
print("Array after adding 5:\n", result)


Original array:
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Array after adding 5:
 [[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]


In [72]:
#37. Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
#   corresponding element in arr1 using NumPy broadcasting

In [73]:
import numpy as np

# Define the arrays
arr1 = np.array([[2, 3, 4]])  # Shape (1, 3)
arr2 = np.array([[1, 2, 3, 4],
                 [5, 6, 7, 8],
                 [9, 10, 11, 12]])  # Shape (3, 4)

# Use broadcasting to multiply each row of arr2 by the corresponding element in arr1
result = arr1.T * arr2

print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Result after broadcasting and multiplication:\n", result)


Array arr1:
 [[2 3 4]]
Array arr2:
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
Result after broadcasting and multiplication:
 [[ 2  4  6  8]
 [15 18 21 24]
 [36 40 44 48]]


In [74]:
#38.  Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
#    NumPy broadcasting.

In [75]:
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3]])  # Shape (1, 3)
arr2 = np.array([[10, 20, 30],
                 [40, 50, 60],
                 [70, 80, 90],
                 [100, 110, 120]])  # Shape (4, 3)

# Add arr1 to each row of arr2 using broadcasting
result = arr2 + arr1

print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Result after broadcasting and addition:\n", result)


Array arr1:
 [[1 2 3]]
Array arr2:
 [[ 10  20  30]
 [ 40  50  60]
 [ 70  80  90]
 [100 110 120]]
Result after broadcasting and addition:
 [[ 11  22  33]
 [ 41  52  63]
 [ 71  82  93]
 [101 112 123]]


In [76]:
#39.   Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
#      broadcasting.

In [77]:
import numpy as np

# Define the arrays
arr1 = np.array([[1],
                 [2],
                 [3]])  # Shape (3, 1)

arr2 = np.array([[10, 20, 30]])  # Shape (1, 3)

# Add the arrays using broadcasting
result = arr1 + arr2

print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Result after broadcasting and addition:\n", result)


Array arr1:
 [[1]
 [2]
 [3]]
Array arr2:
 [[10 20 30]]
Result after broadcasting and addition:
 [[11 21 31]
 [12 22 32]
 [13 23 33]]


In [78]:
#40. Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
#    broadcasting. Handle the shape incompatibility.

In [81]:
import numpy as np

# Define the arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)

arr2 = np.array([[1, 2],
                 [3, 4]])  # Shape (2, 2)

# Reshape arr2 to (2, 1, 2) to make it compatible for broadcasting with arr1
arr2_reshaped = arr2[:, np.newaxis, :]  # Shape becomes (2, 1, 2)

# Now arr1 has shape (2, 3) and arr2_reshaped has shape (2, 1, 2)
# Broadcasting will align them for element-wise multiplication
result = arr1[:, :, np.newaxis] * arr2_reshaped

print("Array arr1:\n", arr1)
print("Array arr2:\n", arr2)
print("Result after broadcasting and multiplication:\n", result)



Array arr1:
 [[1 2 3]
 [4 5 6]]
Array arr2:
 [[1 2]
 [3 4]]
Result after broadcasting and multiplication:
 [[[ 1  2]
  [ 2  4]
  [ 3  6]]

 [[12 16]
  [15 20]
  [18 24]]]


In [82]:
#41. Calculate column wise mean for the given array:
#    arr = np.array([[1, 2, 3], [4, 5, 6]])


In [83]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Calculate the column-wise mean
column_wise_mean = np.mean(arr, axis=0)

print("Column-wise mean:", column_wise_mean)


Column-wise mean: [2.5 3.5 4.5]


In [84]:
#42.  Find maximum value in each row of the given array:
#     arr = np.array([[1, 2, 3], [4, 5, 6]])

In [85]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the maximum value in each row
row_max = np.max(arr, axis=1)

print("Maximum value in each row:", row_max)


Maximum value in each row: [3 6]


In [86]:
#43.  For the given array, find indices of maximum value in each column.
#     arr = np.array([[1, 2, 3], [4, 5, 6]])


In [87]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Find the indices of the maximum value in each column
column_max_indices = np.argmax(arr, axis=0)

print("Indices of maximum values in each column:", column_max_indices)


Indices of maximum values in each column: [1 1 1]


In [88]:
#44. For the given array, apply custom function to calculate moving sum along rows.
#    arr = np.array([[1, 2, 3], [4, 5, 6]])

In [89]:
import numpy as np

# Define the array
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

# Custom function to calculate the moving sum along rows
def moving_sum(arr):
    return np.cumsum(arr, axis=1)

# Apply the custom function
result = moving_sum(arr)

print("Moving sum along rows:\n", result)


Moving sum along rows:
 [[ 1  3  6]
 [ 4  9 15]]


In [90]:
#45.  In the given array, check if all elements in each column are even.
#     arr = np.array([[2, 4, 6], [3, 5, 7]])

In [91]:
import numpy as np

# Define the array
arr = np.array([[2, 4, 6],
                [3, 5, 7]])

# Check if all elements in each column are even
all_even = np.all(np.mod(arr, 2) == 0, axis=0)

print("Are all elements in each column even?", all_even)


Are all elements in each column even? [False False False]


In [92]:
#46.  Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
#     reshaped matrix.
#     original_array = np.array([1, 2, 3, 4, 5, 6])


In [93]:
import numpy as np

# Define the original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Reshape the array into a matrix of dimensions 2x3 (2 rows and 3 columns)
reshaped_matrix = original_array.reshape(2, 3)

print("Reshaped Matrix:\n", reshaped_matrix)


Reshaped Matrix:
 [[1 2 3]
 [4 5 6]]


In [94]:
#47.  Create a function that takes a matrix as input and returns the flattened array.
#     input_matrix = np.array([[1, 2, 3], [4, 5, 6]])


In [95]:
import numpy as np

# Define the function to flatten the matrix
def flatten_matrix(matrix):
    return matrix.flatten()

# Define the input matrix
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# Call the function to flatten the matrix
flattened_array = flatten_matrix(input_matrix)

print("Flattened Array:", flattened_array)


Flattened Array: [1 2 3 4 5 6]


In [96]:
#48. Write a function that concatenates two given arrays along a specified axis.
#    array1 = np.array([[1, 2], [3, 4]])
#    array2 = np.array([[5, 6], [7, 8]])

In [97]:
import numpy as np

# Define the function to concatenate two arrays along a specified axis
def concatenate_arrays(array1, array2, axis):
    return np.concatenate((array1, array2), axis=axis)

# Define the input arrays
array1 = np.array([[1, 2], [3, 4]])
array2 = np.array([[5, 6], [7, 8]])

# Concatenate along axis 0 (vertically)
result_axis_0 = concatenate_arrays(array1, array2, axis=0)
print("Concatenated along axis 0:\n", result_axis_0)

# Concatenate along axis 1 (horizontally)
result_axis_1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1:\n", result_axis_1)


Concatenated along axis 0:
 [[1 2]
 [3 4]
 [5 6]
 [7 8]]

Concatenated along axis 1:
 [[1 2 5 6]
 [3 4 7 8]]


In [98]:
#49. Create a function that splits an array into multiple sub-arrays along a specified axis.
#    original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

In [99]:
import numpy as np

# Define the function to split the array along a specified axis
def split_array(array, axis, num_splits):
    return np.array_split(array, num_splits, axis=axis)

# Define the original array
original_array = np.array([[1, 2, 3],
                           [4, 5, 6],
                           [7, 8, 9]])

# Split the array along axis 0 (rows)
result_axis_0 = split_array(original_array, axis=0, num_splits=3)
print("Array split along axis 0 (rows):")
for sub_array in result_axis_0:
    print(sub_array)

# Split the array along axis 1 (columns)
result_axis_1 = split_array(original_array, axis=1, num_splits=3)
print("\nArray split along axis 1 (columns):")
for sub_array in result_axis_1:
    print(sub_array)


Array split along axis 0 (rows):
[[1 2 3]]
[[4 5 6]]
[[7 8 9]]

Array split along axis 1 (columns):
[[1]
 [4]
 [7]]
[[2]
 [5]
 [8]]
[[3]
 [6]
 [9]]


In [100]:
#50. Write a function that inserts and then deletes elements from a given array at specified indices.
#    original_array = np.array([1, 2, 3, 4, 5])
#    indices_to_insert = [2, 4]
#    values_to_insert = [10, 11]
#    indices_to_delete = [1, 3]

In [101]:
import numpy as np

# Define the function to insert and delete elements
def modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    # Insert elements at specified indices
    modified_array = np.insert(original_array, indices_to_insert, values_to_insert)

    # Delete elements at specified indices
    modified_array = np.delete(modified_array, indices_to_delete)

    return modified_array

# Define the original array
original_array = np.array([1, 2, 3, 4, 5])

# Indices and values for insertion
indices_to_insert = [2, 4]
values_to_insert = [10, 11]

# Indices for deletion
indices_to_delete = [1, 3]

# Call the function to modify the array
result_array = modify_array(original_array, indices_to_insert, values_to_insert, indices_to_delete)

print("Modified Array:", result_array)


Modified Array: [ 1 10  4 11  5]


In [102]:
#51. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
#    Perform element-wise addition between `arr1` and `arr2`.

In [103]:
import numpy as np

# Create a random integer array arr1 of shape (3, 3) with values between 1 and 100
arr1 = np.random.randint(1, 100, size=(3, 3))

# Create an array arr2 with integers from 1 to 10
arr2 = np.arange(1, 10).reshape(3, 3)

# Perform element-wise addition
result = arr1 + arr2

# Print the arrays and the result
print("Array 1 (Random Integers):\n", arr1)
print("\nArray 2 (Integers from 1 to 10):\n", arr2)
print("\nElement-wise Addition Result:\n", result)


Array 1 (Random Integers):
 [[76 77 15]
 [49 58 98]
 [40 27 25]]

Array 2 (Integers from 1 to 10):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]

Element-wise Addition Result:
 [[ 77  79  18]
 [ 53  63 104]
 [ 47  35  34]]


In [104]:
#52. Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
#    from 1 to 10. Subtract `arr2` from `arr1` element-wise.

In [105]:
import numpy as np

# Generate arr1 with sequential integers from 10 to 1 (descending order)
arr1 = np.arange(10, 0, -1)

# Generate arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)

# Perform element-wise subtraction
result = arr1 - arr2

# Print the arrays and the result
print("Array 1 (Sequential integers from 10 to 1):\n", arr1)
print("\nArray 2 (Integers from 1 to 10):\n", arr2)
print("\nElement-wise Subtraction Result (arr1 - arr2):\n", result)


Array 1 (Sequential integers from 10 to 1):
 [10  9  8  7  6  5  4  3  2  1]

Array 2 (Integers from 1 to 10):
 [ 1  2  3  4  5  6  7  8  9 10]

Element-wise Subtraction Result (arr1 - arr2):
 [ 9  7  5  3  1 -1 -3 -5 -7 -9]


In [106]:
#53. Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
#    Perform element-wise multiplication between `arr1` and `arr2`.

In [108]:
import numpy as np

# Create arr1 with random integers, for example, in the range 1 to 10, and shape (3, 3)
arr1 = np.random.randint(1, 10, size=(3, 3))

# Create arr2 with integers from 1 to 3 (3 values), reshaped to match the rows of arr1
arr2 = np.arange(1, 4).reshape(3, 1)  # Shape is (3, 1), so it can be broadcast across arr1

# Perform element-wise multiplication
result = arr1 * arr2

# Print the arrays and the result
print("Array 1 (Random Integers):\n", arr1)
print("\nArray 2 (Integers from 1 to 3, reshaped):\n", arr2)
print("\nElement-wise Multiplication Result:\n", result)




Array 1 (Random Integers):
 [[7 7 4]
 [9 9 7]
 [6 7 9]]

Array 2 (Integers from 1 to 3, reshaped):
 [[1]
 [2]
 [3]]

Element-wise Multiplication Result:
 [[ 7  7  4]
 [18 18 14]
 [18 21 27]]


In [109]:
#54. Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
#    to 5. Perform element-wise division of `arr1` by `arr2`.

In [110]:
import numpy as np

# Create arr1 with even integers from 2 to 10
arr1 = np.arange(2, 11, 2)

# Create arr2 with integers from 1 to 5
arr2 = np.arange(1, 6)

# Perform element-wise division
result = arr1 / arr2

# Print the arrays and the result
print("Array 1 (Even Integers from 2 to 10):\n", arr1)
print("\nArray 2 (Integers from 1 to 5):\n", arr2)
print("\nElement-wise Division Result:\n", result)


Array 1 (Even Integers from 2 to 10):
 [ 2  4  6  8 10]

Array 2 (Integers from 1 to 5):
 [1 2 3 4 5]

Element-wise Division Result:
 [2. 2. 2. 2. 2.]


In [111]:
#55. Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
#    reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

In [112]:
import numpy as np

# Create arr1 with integers from 1 to 5
arr1 = np.array([1, 2, 3, 4, 5])

# Create arr2 with the same numbers reversed
arr2 = arr1[::-1]

# Perform element-wise exponentiation (arr1 raised to the power of arr2)
result = np.power(arr1, arr2)

# Print the arrays and the result
print("Array 1 (Integers from 1 to 5):\n", arr1)
print("\nArray 2 (Reversed of Array 1):\n", arr2)
print("\nElement-wise Exponentiation Result (arr1^arr2):\n", result)


Array 1 (Integers from 1 to 5):
 [1 2 3 4 5]

Array 2 (Reversed of Array 1):
 [5 4 3 2 1]

Element-wise Exponentiation Result (arr1^arr2):
 [ 1 16 27 16  5]


In [113]:
#56. Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
#    arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

In [114]:
import numpy as np

def count_substring_occurrences(arr, substring):
    # Use np.char.count to count occurrences of substring in each element of the array
    count_array = np.char.count(arr, substring)
    # Sum the occurrences to get the total count
    total_count = count_array.sum()
    return total_count

# Example array
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Count occurrences of the substring 'hello'
substring = 'hello'
result = count_substring_occurrences(arr, substring)

print(f"Occurrences of '{substring}': {result}")


Occurrences of 'hello': 3


In [3]:
#57. Write a function that extracts uppercase characters from a NumPy array of strings.
# arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

In [2]:
import numpy as np

def extract_uppercase(arr):
    # Use np.char to iterate over each string in the array and extract uppercase characters
    uppercase_chars = [ ''.join([char for char in word if char.isupper()]) for word in arr ]
    return np.array(uppercase_chars)

# Example array
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Extract uppercase characters
result = extract_uppercase(arr)

print(f"Extracted Uppercase Characters:\n", result)


Extracted Uppercase Characters:
 ['H' 'W' 'OAI' 'GPT']


In [4]:
#58.  Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
#     arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [5]:
import numpy as np

def replace_substring(arr, old_substring, new_substring):
    # Use np.char.replace to replace occurrences of old_substring with new_substring
    return np.char.replace(arr, old_substring, new_substring)

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Replace occurrences of 'apple' with 'orange'
old_substring = 'apple'
new_substring = 'orange'

# Get the result after replacement
result = replace_substring(arr, old_substring, new_substring)

print(f"Array after replacement:\n", result)


Array after replacement:
 ['orange' 'banana' 'grape' 'pineorange']


In [6]:
#59. Write a function that concatenates strings in a NumPy array element-wise.
#    arr1 = np.array(['Hello', 'World'])
#    arr2 = np.array(['Open', 'AI'])

In [7]:
import numpy as np

def concatenate_strings(arr1, arr2):
    # Use np.char.add to concatenate strings element-wise
    return np.char.add(arr1, arr2)

# Example arrays
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Concatenate the strings element-wise
result = concatenate_strings(arr1, arr2)

print(f"Concatenated Array:\n", result)


Concatenated Array:
 ['HelloOpen' 'WorldAI']


In [8]:
#60. Write a function that finds the length of the longest string in a NumPy array.
#    arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

In [9]:
import numpy as np

def longest_string_length(arr):
    # Use np.char.str_len to find the length of each string
    string_lengths = np.char.str_len(arr)
    # Find the maximum length
    return np.max(string_lengths)

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Find the length of the longest string
result = longest_string_length(arr)

print(f"The length of the longest string is: {result}")


The length of the longest string is: 9


In [10]:
#61. Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
#    standard deviation of the dataset using NumPy's functions.

In [11]:
import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
dataset = np.random.randint(1, 1001, 100)

# Compute the mean, median, variance, and standard deviation
mean = np.mean(dataset)
median = np.median(dataset)
variance = np.var(dataset)
std_dev = np.std(dataset)

# Print the results
print(f"Mean: {mean}")
print(f"Median: {median}")
print(f"Variance: {variance}")
print(f"Standard Deviation: {std_dev}")


Mean: 512.65
Median: 546.0
Variance: 77757.48749999999
Standard Deviation: 278.8502958578312


In [12]:
#62.  Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
#     dataset.

In [13]:
import numpy as np

# Generate an array of 50 random numbers between 1 and 100
dataset = np.random.randint(1, 101, 50)

# Find the 25th and 75th percentiles of the dataset
percentile_25 = np.percentile(dataset, 25)
percentile_75 = np.percentile(dataset, 75)

# Print the results
print(f"25th Percentile: {percentile_25}")
print(f"75th Percentile: {percentile_75}")


25th Percentile: 33.0
75th Percentile: 82.5


In [14]:
#63. Create two arrays representing two sets of variables. Compute the correlation coefficient between these
#    arrays using NumPy's `corrcoef` function.

In [15]:
import numpy as np

# Create two arrays representing two sets of variables
arr1 = np.array([1, 2, 3, 4, 5])
arr2 = np.array([5, 4, 3, 2, 1])

# Compute the correlation coefficient between the two arrays
correlation_matrix = np.corrcoef(arr1, arr2)

# Extract the correlation coefficient from the matrix
correlation_coefficient = correlation_matrix[0, 1]

# Print the correlation coefficient
print(f"Correlation Coefficient: {correlation_coefficient}")


Correlation Coefficient: -0.9999999999999999


In [16]:
#64.  Create two matrices and perform matrix multiplication using NumPy's `dot` function.

In [17]:
import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2], [3, 4]])
matrix2 = np.array([[5, 6], [7, 8]])

# Perform matrix multiplication using np.dot
result = np.dot(matrix1, matrix2)

# Print the result
print("Result of matrix multiplication:")
print(result)


Result of matrix multiplication:
[[19 22]
 [43 50]]


In [18]:
#65. Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
#    percentiles along with the first and third quartiles.

In [19]:
import numpy as np

# Generate an array of 50 integers between 10 and 1000
arr = np.random.randint(10, 1001, 50)

# Calculate the 10th, 50th (median), and 90th percentiles
percentile_10 = np.percentile(arr, 10)
percentile_50 = np.percentile(arr, 50)  # This is also the median
percentile_90 = np.percentile(arr, 90)

# Calculate the first and third quartiles
q1 = np.percentile(arr, 25)
q3 = np.percentile(arr, 75)

# Print the results
print(f"10th Percentile: {percentile_10}")
print(f"50th Percentile (Median): {percentile_50}")
print(f"90th Percentile: {percentile_90}")
print(f"First Quartile (Q1): {q1}")
print(f"Third Quartile (Q3): {q3}")


10th Percentile: 106.2
50th Percentile (Median): 586.5
90th Percentile: 935.0
First Quartile (Q1): 287.75
Third Quartile (Q3): 807.75


In [20]:
#66.  Create a NumPy array of integers and find the index of a specific element

In [21]:
import numpy as np

# Create a NumPy array of integers
arr = np.array([10, 20, 30, 40, 50])

# Specify the element you want to find
element = 30

# Find the index of the specified element
index = np.where(arr == element)

# Print the index
print(f"The index of {element} is: {index[0][0]}")


The index of 30 is: 2


In [22]:
#67.  Generate a random NumPy array and sort it in ascending order.

In [23]:
import numpy as np

# Generate a random NumPy array with 10 random integers between 1 and 100
arr = np.random.randint(1, 101, 10)

# Sort the array in ascending order
sorted_arr = np.sort(arr)

# Print the original and sorted arrays
print("Original Array:", arr)
print("Sorted Array:", sorted_arr)


Original Array: [50 97 79 49 95 73  9 35 70 66]
Sorted Array: [ 9 35 49 50 66 70 73 79 95 97]


In [24]:
#68.  Filter elements >20  in the given NumPy array
#     arr = np.array([12, 25, 6, 42, 8, 30])

In [25]:
import numpy as np

# Given array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements greater than 20
filtered_arr = arr[arr > 20]

# Print the filtered array
print("Filtered Array:", filtered_arr)


Filtered Array: [25 42 30]


In [26]:
#69.  Filter elements which are divisible by 3 from a given NumPy array
#     arr = np.array([1, 5, 8, 12, 15])

In [27]:
import numpy as np

# Given array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_arr = arr[arr % 3 == 0]

# Print the filtered array
print("Filtered Array:", filtered_arr)


Filtered Array: [12 15]


In [28]:
#70. Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
#    arr = np.array([10, 20, 30, 40, 50])

In [29]:
import numpy as np

# Given array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements between 20 and 40 (inclusive)
filtered_arr = arr[(arr >= 20) & (arr <= 40)]

# Print the filtered array
print("Filtered Array:", filtered_arr)


Filtered Array: [20 30 40]


In [30]:
#71. For the given NumPy array, check its byte order using the dtype attribute byteorder
#    arr = np.array([1, 2, 3])

In [31]:
import numpy as np

# Given array
arr = np.array([1, 2, 3])

# Check the byte order using dtype.byteorder
byte_order = arr.dtype.byteorder

# Print the byte order
print("Byte order:", byte_order)


Byte order: =


In [32]:
#72. For the given NumPy array, perform byte swapping in place using `byteswap()`.
#    arr = np.array([1, 2, 3], dtype=np.int32)

In [33]:
import numpy as np

# Given array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Perform byte swapping in place
arr.byteswap(True)

# Print the array after byte swapping
print("Array after byte swapping:", arr)


Array after byte swapping: [16777216 33554432 50331648]


In [34]:
#73. For the given NumPy array, swap its byte order without modifying the original array using
#    `newbyteorder()`.
#    arr = np.array([1, 2, 3], dtype=np.int32)

In [35]:
import numpy as np

# Given array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Swap the byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print the original and the new array
print("Original Array:", arr)
print("Array with swapped byte order:", swapped_arr)


Original Array: [1 2 3]
Array with swapped byte order: [16777216 33554432 50331648]


In [36]:
#74. For the given NumPy array and swap its byte order conditionally based on system endianness using
#    `newbyteorder()`.
#    arr = np.array([1, 2, 3], dtype=np.int32)

In [37]:
import numpy as np
import sys

# Given array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Get the system's byte order
system_endianness = sys.byteorder

# Check if the system's byte order differs from the array's byte order
if arr.dtype.byteorder != system_endianness:
    # Swap the byte order conditionally based on system endianness
    swapped_arr = arr.newbyteorder()
else:
    # No need to swap if the byte order matches the system's endianness
    swapped_arr = arr

# Print the original and the conditionally swapped array
print("Original Array:", arr)
print("Conditionally Byte Swapped Array:", swapped_arr)


Original Array: [1 2 3]
Conditionally Byte Swapped Array: [16777216 33554432 50331648]


In [38]:
#75. For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
#    attribute `byteorder`.
#    arr = np.array([1, 2, 3], dtype=np.int32)

In [39]:
import numpy as np
import sys

# Given array with dtype=np.int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Get the system's byte order
system_endianness = sys.byteorder

# Check if the byte order of the array differs from the system's byte order
if arr.dtype.byteorder != system_endianness:
    print("Byte swapping is necessary.")
else:
    print("Byte swapping is not necessary.")


Byte swapping is necessary.


In [40]:
#76. Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
#    an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

In [41]:
import numpy as np

# Create an array with values from 1 to 10
arr1 = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Create a copy of arr1
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100

# Print both arrays to see if arr1 is affected
print("Original array (arr1):", arr1)
print("Modified copy array (copy_arr):", copy_arr)


Original array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
Modified copy array (copy_arr): [100   2   3   4   5   6   7   8   9  10]


In [42]:
#77. Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
#    the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

In [43]:
import numpy as np

# Create a 2D NumPy array (3x3) with random integers
matrix = np.random.randint(1, 100, size=(3, 3))

# Extract a slice from the matrix (e.g., the first two rows and columns)
view_slice = matrix[:2, :2]

# Print the original matrix and the slice
print("Original matrix (matrix):")
print(matrix)

print("\nSlice (view_slice):")
print(view_slice)

# Modify an element in the slice
view_slice[0, 0] = 999

# Print the modified slice and the original matrix after modification
print("\nModified slice (view_slice):")
print(view_slice)

print("\nOriginal matrix (matrix) after modifying slice:")
print(matrix)


Original matrix (matrix):
[[45 15 99]
 [77 26 77]
 [80 36 60]]

Slice (view_slice):
[[45 15]
 [77 26]]

Modified slice (view_slice):
[[999  15]
 [ 77  26]]

Original matrix (matrix) after modifying slice:
[[999  15  99]
 [ 77  26  77]
 [ 80  36  60]]


In [44]:
#78. Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
#    `view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

In [45]:
import numpy as np

# Create a 2D NumPy array of shape (4, 3) with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Extract a slice (view) from the array (e.g., the first two rows and columns)
view_b = array_a[:2, :2]

# Print the original array and the slice
print("Original array (array_a):")
print(array_a)

print("\nSlice (view_b):")
print(view_b)

# Broadcast the addition of 5 to the slice
view_b += 5

# Print the modified slice and the original array after the modification
print("\nModified slice (view_b) after adding 5:")
print(view_b)

print("\nOriginal array (array_a) after modifying slice:")
print(array_a)


Original array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

Slice (view_b):
[[1 2]
 [4 5]]

Modified slice (view_b) after adding 5:
[[ 6  7]
 [ 9 10]]

Original array (array_a) after modifying slice:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]


In [46]:
#79. Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
#    `reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
#    reflects changes in the original `orig_array`.

In [47]:
import numpy as np

# Create a NumPy array 'orig_array' of shape (2, 4) with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Create a reshaped view 'reshaped_view' of shape (4, 2) from 'orig_array'
reshaped_view = orig_array.reshape(4, 2)

# Print the original array and reshaped view
print("Original array (orig_array):")
print(orig_array)

print("\nReshaped view (reshaped_view):")
print(reshaped_view)

# Modify an element in the reshaped view (e.g., change element at index [1, 1])
reshaped_view[1, 1] = 99

# Print the modified reshaped view and the original array after modification
print("\nModified reshaped view (reshaped_view):")
print(reshaped_view)

print("\nOriginal array (orig_array) after modifying reshaped view:")
print(orig_array)


Original array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]

Reshaped view (reshaped_view):
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

Modified reshaped view (reshaped_view):
[[ 1  2]
 [ 3 99]
 [ 5  6]
 [ 7  8]]

Original array (orig_array) after modifying reshaped view:
[[ 1  2  3 99]
 [ 5  6  7  8]]


In [48]:
#80. Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
#    elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

In [50]:
import numpy as np

# Create a NumPy array 'data' of shape (3, 4) with random integers
data = np.random.randint(1, 10, size=(3, 4))

# Print the original 'data' array
print("Original data array:")
print(data)

# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Print the 'data_copy' array
print("\nExtracted data_copy (elements > 5):")
print(data_copy)

# Modify an element in the 'data_copy'
data_copy[0] = 99

# Print the modified 'data_copy' array
print("\nModified data_copy:")
print(data_copy)

# Print the original 'data' array after modification
print("\nOriginal data array after modifying data_copy:")
print(data)


Original data array:
[[7 6 4 5]
 [4 8 9 8]
 [9 4 9 4]]

Extracted data_copy (elements > 5):
[7 6 8 9 8 9 9]

Modified data_copy:
[99  6  8  9  8  9  9]

Original data array after modifying data_copy:
[[7 6 4 5]
 [4 8 9 8]
 [9 4 9 4]]


In [51]:
#81.  Create two matrices A and B of identical shape containing integers and perform addition and subtraction
#     operations between them.

In [52]:
import numpy as np

# Create two matrices A and B of identical shape containing random integers
A = np.random.randint(1, 10, size=(3, 3))  # 3x3 matrix with random integers from 1 to 9
B = np.random.randint(1, 10, size=(3, 3))  # 3x3 matrix with random integers from 1 to 9

# Print the original matrices
print("Matrix A:")
print(A)

print("\nMatrix B:")
print(B)

# Perform addition operation
addition_result = A + B
print("\nAddition (A + B):")
print(addition_result)

# Perform subtraction operation
subtraction_result = A - B
print("\nSubtraction (A - B):")
print(subtraction_result)


Matrix A:
[[6 7 3]
 [8 7 9]
 [6 8 7]]

Matrix B:
[[5 9 5]
 [6 9 9]
 [4 4 5]]

Addition (A + B):
[[11 16  8]
 [14 16 18]
 [10 12 12]]

Subtraction (A - B):
[[ 1 -2 -2]
 [ 2 -2  0]
 [ 2  4  2]]


In [53]:
#82. Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

In [54]:
import numpy as np

# Create matrix C of shape (3, 2) with random integers
C = np.random.randint(1, 10, size=(3, 2))

# Create matrix D of shape (2, 4) with random integers
D = np.random.randint(1, 10, size=(2, 4))

# Print the matrices
print("Matrix C (3x2):")
print(C)

print("\nMatrix D (2x4):")
print(D)

# Perform matrix multiplication (C * D)
result = np.dot(C, D)

# Alternatively, you can use the '@' operator for matrix multiplication
# result = C @ D

# Print the result of matrix multiplication
print("\nMatrix multiplication result (C * D):")
print(result)


Matrix C (3x2):
[[1 3]
 [6 3]
 [3 3]]

Matrix D (2x4):
[[3 4 6 7]
 [3 2 9 3]]

Matrix multiplication result (C * D):
[[12 10 33 16]
 [27 30 63 51]
 [18 18 45 30]]


In [55]:
#83. Create a matrix `E` and find its transpose

In [56]:
import numpy as np

# Create matrix E with random integers, for example a 3x2 matrix
E = np.random.randint(1, 10, size=(3, 2))

# Print the original matrix E
print("Matrix E:")
print(E)

# Find the transpose of matrix E
E_transpose = np.transpose(E)

# Alternatively, you can use the shorthand .T
# E_transpose = E.T

# Print the transpose of matrix E
print("\nTranspose of Matrix E:")
print(E_transpose)


Matrix E:
[[3 2]
 [9 6]
 [7 7]]

Transpose of Matrix E:
[[3 9 7]
 [2 6 7]]


In [57]:
#84. Generate a square matrix `F` and compute its determinant

In [58]:
import numpy as np

# Create a square matrix F (for example, a 3x3 matrix)
F = np.random.randint(1, 10, size=(3, 3))

# Print the original matrix F
print("Matrix F:")
print(F)

# Compute the determinant of matrix F
det_F = np.linalg.det(F)

# Print the determinant
print("\nDeterminant of Matrix F:")
print(det_F)


Matrix F:
[[7 2 6]
 [5 5 4]
 [5 5 7]]

Determinant of Matrix F:
75.00000000000004


In [59]:
#85. Create a square matrix `G` and find its inverse.

In [60]:
import numpy as np

# Create a square matrix G (for example, a 3x3 matrix)
G = np.random.randint(1, 10, size=(3, 3))

# Print the original matrix G
print("Matrix G:")
print(G)

# Check if the matrix is invertible (determinant should not be zero)
det_G = np.linalg.det(G)

if det_G != 0:
    # Compute the inverse of matrix G
    G_inverse = np.linalg.inv(G)

    # Print the inverse of matrix G
    print("\nInverse of Matrix G:")
    print(G_inverse)
else:
    print("\nMatrix G is singular, and cannot be inverted (determinant is 0).")


Matrix G:
[[6 9 7]
 [6 6 9]
 [4 8 8]]

Inverse of Matrix G:
[[ 0.28571429  0.19047619 -0.46428571]
 [ 0.14285714 -0.23809524  0.14285714]
 [-0.28571429  0.14285714  0.21428571]]
